version: '3.8'

services:
  web-agent:
    build: .
    container_name: web-agent
    ports:
      - "8000:8000"  # This will be overridden by the deployment API
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs  # Optional: for persistent logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge
